services:
  liquidsoap:
    image: savonet/liquidsoap:v2.2.5
    container_name: radio-liquidsoap
    restart: unless-stopped
    volumes:
      - /data/radio/config/radio.liq:/etc/liquidsoap/radio.liq
      - radio-music:/music/songs
    command: /etc/liquidsoap/radio.liq
    networks:
      - radio-net

  ftp:
    image: stilliard/pure-ftpd:hardened
    container_name: radio-ftp
    restart: unless-stopped
    ports:
      - "${FTP_PORT}:21"
      - "${FTP_PASSIVE_MIN}-${FTP_PASSIVE_MAX}:${FTP_PASSIVE_MIN}-${FTP_PASSIVE_MAX}"
    volumes:
      - radio-music:/home/radio/music/songs
      - radio-interludios:/home/radio/music/interludios
    environment:
      - PUBLICHOST=${FTP_PUBLIC_HOST}
      - FTP_USER_NAME=${FTP_USER_NAME}
      - FTP_USER_PASS=${FTP_USER_PASS}
      - FTP_USER_HOME=${FTP_USER_HOME}
      - UMASK=${FTP_UMASK}
      - TLS_CN=${FTP_PUBLIC_HOST}
    networks:
      - radio-net

volumes:
  radio-music:
  radio-interludios:

networks:
  radio-net:
