import { existsSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { EdgeTTS } from "edge-tts-universal";
import type { Track } from "../domain/types";
import type { LibraryRepository } from "../repositories/sqlite/library.repo";
import type { LiquidsoapService } from "./liquidsoap.service";

interface DialogueMessage {
  role: "user" | "assistant" | "system";
  content: string;
}

interface DjHistory {
  dialogueHistory: DialogueMessage[];
}

export class OrchestratorService {
  private loopInterval: Timer | null = null;
  private isProcessing = false;
  private recentHistory: string[] = []; // Last 15 song IDs queued
  private tempFiles = new Set<string>(); // Keep track of absolute paths of generated MP3s
  private songsQueuedCount = 0; // Number of songs queued since last DJ speech
  private dialogueHistory: DialogueMessage[] = [];

  constructor(
    private readonly libraryRepo: LibraryRepository,
    private readonly liquidsoapService: LiquidsoapService,
    private readonly musicDir: string,
    private readonly dataDir: string
  ) {}

  /**
   * Starts the background queue orchestrator loop.
   */
  public start(): void {
    const isEnabled = process.env.AI_DJ_ENABLED === "true";
    const apiKey = process.env.OPENROUTER_API_KEY || "";

    if (!isEnabled) {
      console.log(
        "[OrchestratorService] AI DJ is disabled via environment variables (AI_DJ_ENABLED)."
      );
      return;
    }

    if (!apiKey) {
      console.error(
        "[OrchestratorService] AI DJ is enabled but OPENROUTER_API_KEY is not configured. AI DJ will not start."
      );
      return;
    }

    // Load persistent history
    this.loadHistory();

    console.log("[OrchestratorService] Starting AI DJ Orchestrator background loop...");
    // Check every 10 seconds
    this.loopInterval = setInterval(() => {
      this.tick().catch((err) => console.error("[OrchestratorService] Error in tick loop:", err));
    }, 10000);

    // Initial trigger
    this.tick().catch((err) => console.error("[OrchestratorService] Error in initial tick:", err));
  }

  /**
   * Stops the background orchestrator loop.
   */
  public stop(): void {
    if (this.loopInterval) {
      clearInterval(this.loopInterval);
      this.loopInterval = null;
    }
    console.log("[OrchestratorService] AI DJ Orchestrator stopped.");
  }

  /**
   * Loads dialogue history from a file.
   */
  private loadHistory(): void {
    const filePath = join(this.dataDir, "dj_history.json");
    if (existsSync(filePath)) {
      try {
        const content = readFileSync(filePath, "utf-8");
        const data = JSON.parse(content) as DjHistory;
        this.dialogueHistory = data.dialogueHistory || [];
        console.log(
          `[OrchestratorService] Loaded ${this.dialogueHistory.length} dialogue history items from dj_history.json`
        );
      } catch (err: any) {
        console.error(
          "[OrchestratorService] Failed to load dj_history.json, starting fresh:",
          err.message
        );
        this.dialogueHistory = [];
      }
    } else {
      this.dialogueHistory = [];
    }
  }

  /**
   * Saves dialogue history to a file.
   */
  private saveHistory(): void {
    const filePath = join(this.dataDir, "dj_history.json");
    try {
      const data: DjHistory = { dialogueHistory: this.dialogueHistory };
      writeFileSync(filePath, JSON.stringify(data, null, 2), "utf-8");
    } catch (err: any) {
      console.error("[OrchestratorService] Failed to save dj_history.json:", err.message);
    }
  }

  /**
   * Periodically checking queue and streams.
   */
  private async tick(): Promise<void> {
    if (this.isProcessing) return;
    this.isProcessing = true;

    try {
      if (!this.liquidsoapService.isConnected()) {
        this.isProcessing = false;
        return;
      }

      const status = await this.liquidsoapService.getStreamStatus();
      const queue = await this.liquidsoapService.queueList();

      // 1. Clean up generated TTS files that already played
      await this.cleanupTempFiles(status, queue);

      // 2. Queue new tracks if queue is dropping below 2 elements
      if (queue.length < 2) {
        console.log(
          `[OrchestratorService] Queue is low (${queue.length} items). Enqueuing next track...`
        );
        await this.enqueueNext(status, queue);
      }
    } catch (err: any) {
      console.error("[OrchestratorService] Error in loop tick:", err.message);
    } finally {
      this.isProcessing = false;
    }
  }

  /**
   * Cleans up physical temporary files generated by the DJ TTS synthesizer after playing.
   */
  private async cleanupTempFiles(status: any, queue: any[]): Promise<void> {
    const currentPlayingFile = status.metadata?.filename || status.metadata?.initial_uri || "";

    const queuedFilenames = new Set<string>();
    for (const item of queue) {
      const meta = await this.liquidsoapService.getRequestMetadata(item.rid);
      const filename = meta.filename || meta.initial_uri || "";
      if (filename) queuedFilenames.add(filename);
    }

    for (const tempFile of Array.from(this.tempFiles)) {
      const baseFilename = tempFile.replace(/\\/g, "/").split("/").pop();
      if (!baseFilename) continue;

      const isCurrentlyPlaying = currentPlayingFile.includes(baseFilename);
      const isQueued = Array.from(queuedFilenames).some((fn) => fn.includes(baseFilename));

      if (!isCurrentlyPlaying && !isQueued) {
        try {
          if (existsSync(tempFile)) {
            unlinkSync(tempFile);
            console.log(`[OrchestratorService] Cleaned up temporary DJ speech: ${tempFile}`);
          }
          this.tempFiles.delete(tempFile);
        } catch (err: any) {
          console.error(
            `[OrchestratorService] Failed to clean up temp file ${tempFile}:`,
            err.message
          );
        }
      }
    }
  }

  /**
   * Enqueues the next track, deciding between a DJ speech + song or just a song.
   */
  private async enqueueNext(status: any, queue: any[]): Promise<void> {
    const songsBetween = parseInt(process.env.AI_DJ_SONGS_BETWEEN || "3", 10);
    const allSongs = this.libraryRepo.getAllTracks("song");

    if (allSongs.length === 0) {
      console.warn(
        "[OrchestratorService] No tracks found in the database catalog. Queue addition skipped."
      );
      return;
    }

    // Determine the last song queued or currently playing
    let lastSong: Track | null = null;
    if (queue.length > 0) {
      const lastQueueItem = queue[queue.length - 1];
      const meta = await this.liquidsoapService.getRequestMetadata(lastQueueItem.rid);
      const filename = meta.filename || meta.initial_uri || "";
      if (filename) {
        const relativePath = filename
          .replace(/\\/g, "/")
          .replace(/^\/music\//, "")
          .replace(/^\/app\/music\//, "")
          .replace(/^app\/music\//, "");
        lastSong = this.libraryRepo.getTrackByFile(relativePath);
      }
    }

    if (!lastSong && status.playing && status.metadata) {
      const filename = status.metadata.filename || status.metadata.initial_uri || "";
      if (filename) {
        const relativePath = filename
          .replace(/\\/g, "/")
          .replace(/^\/music\//, "")
          .replace(/^\/app\/music\//, "")
          .replace(/^app\/music\//, "");
        lastSong = this.libraryRepo.getTrackByFile(relativePath);
      }
    }

    // Is it time for an AI DJ speech?
    const isInterludeTime = this.songsQueuedCount >= songsBetween;

    console.log(
      `[OrchestratorService] Triggering agent. Interlude time: ${isInterludeTime}. Songs queued since last DJ speech: ${this.songsQueuedCount}`
    );

    const agentResult = await this.runAgentLoop(isInterludeTime);

    let nextSong: Track | null = null;
    if (agentResult?.selectedSongId) {
      nextSong = this.libraryRepo.getTrackById(agentResult.selectedSongId);
      if (!nextSong) {
        console.warn(
          `[OrchestratorService] Agent selected an invalid song ID: ${agentResult.selectedSongId}. Falling back to random selection.`
        );
      }
    }

    // Fallback: pick a random song from DB not recently played
    if (!nextSong) {
      const candidates = allSongs.filter((song) => !this.recentHistory.includes(song.id));
      const pool = candidates.length > 0 ? candidates : allSongs;
      nextSong = pool[Math.floor(Math.random() * pool.length)];
    }

    if (!nextSong) return;

    // Handle DJ speech if generated
    if (isInterludeTime && agentResult?.djScript) {
      const speechPath = await this.synthesizeSpeech(agentResult.djScript);
      if (speechPath) {
        console.log(`[OrchestratorService] Enqueuing synthesized DJ speech track: ${speechPath}`);
        const filename = speechPath.replace(/\\/g, "/").split("/").pop();
        const rid = await this.liquidsoapService.queuePush(`/music/interludios/${filename}`);
        if (rid) {
          this.tempFiles.add(speechPath);
        }

        // Add to dialogue history
        if (lastSong) {
          this.dialogueHistory.push({
            role: "system",
            content: `Sonó la canción: "${lastSong.title}" de ${lastSong.artist || "Desconocido"}`,
          });
        }
        this.dialogueHistory.push({
          role: "assistant",
          content: agentResult.djScript,
        });

        // Trim and save history
        if (this.dialogueHistory.length > 20) {
          this.dialogueHistory = this.dialogueHistory.slice(-20);
        }
        this.saveHistory();
      }
      this.songsQueuedCount = 0; // Reset counter
    } else {
      // Increment counter for standard transition
      this.songsQueuedCount++;
    }

    // Enqueue the selected song
    console.log(
      `[OrchestratorService] Enqueuing Song: "${nextSong.title}" by ${nextSong.artist || "Unknown"}`
    );
    const songRid = await this.liquidsoapService.queuePush(`/music/${nextSong.file}`);
    if (songRid) {
      this.recentHistory.push(nextSong.id);
      if (this.recentHistory.length > 15) this.recentHistory.shift();
    }
  }

  /**
   * Run the LLM agentic tool-use loop.
   */
  private async runAgentLoop(
    isInterlude: boolean
  ): Promise<{ selectedSongId: string; djScript?: string } | null> {
    const apiKey = process.env.OPENROUTER_API_KEY || "";
    const model = process.env.AI_DJ_OPENROUTER_MODEL || "google/gemini-2.5-flash";
    const personality =
      process.env.AI_DJ_PERSONALITY ||
      "Un locutor de radio fresco, entusiasta, moderno y cercano al público de Radio Bloom. Cuenta curiosidades rápidas y hace comentarios ingeniosos.";

    const allSongs = this.libraryRepo.getAllTracks("song");
    const candidates = allSongs.filter((song) => !this.recentHistory.includes(song.id));
    const pool = candidates.length > 0 ? candidates : allSongs;
    const shuffled = [...pool].sort(() => 0.5 - Math.random());
    const subset = shuffled.slice(0, 15);
    const suggestedSongsText = subset
      .map((s) => `- ID: "${s.id}", Título: "${s.title}", Artista: "${s.artist || "Desconocido"}"`)
      .join("\n");

    const systemPrompt = `Eres "DJ Bloom", el orquestador y locutor estrella de la emisora por internet 'Radio Bloom'.
Tu personalidad al aire es: ${personality}

Tu tarea actual es programar la siguiente canción que sonará en el stream.
${
  isInterlude
    ? "ATENCIÓN: Es hora de hablar al micrófono (DJ Speech). Debes seleccionar la siguiente canción de tu biblioteca local Y redactar el guión de locución que leerás en el aire antes de que suene."
    : "ATENCIÓN: Solo debes seleccionar la siguiente canción de tu biblioteca local. No es necesario que escribas un guión de locución en esta ocasión."
}

Canciones sugeridas disponibles actualmente (puedes elegir uno de sus IDs directamente o buscar otros usando tus herramientas):
${suggestedSongsText}

Puedes ejecutar herramientas de tu entorno para obtener información antes de decidir. Responde SIEMPRE con un objeto JSON.

Herramientas disponibles:
- search_library(query: string): busca canciones en la base de datos de la radio por texto (título, artista, álbum).
- get_library_stats(): obtiene el total de canciones disponibles en la base de datos local.
- get_stream_status(): consulta qué canción está sonando actualmente y qué temas están ya en la cola de Liquidsoap.
- get_current_time(): obtiene la hora local de la emisora.

Cuando decidas la canción (y redactes el guión si es hora de locutar), responde EXACTAMENTE con esta estructura JSON de respuesta final:
{
  "action": "final_response",
  "selected_song_id": "ID_REAL_DE_LA_CANCION_DE_TU_BIBLIOTECA",
  "dj_script": "${isInterlude ? "Tu guión completo de locución (en español, de 30 a 45 palabras)." : ""}"
}

Reglas críticas:
1. El 'selected_song_id' DEBE corresponder a una canción real existente en tu biblioteca. Usa las herramientas de búsqueda para encontrar los IDs correctos.
2. Si es hora de locutar, redacta un guión fresco y dinámico según tu personalidad. Puedes saludar, hacer chistes, despedir la canción que estaba sonando e introducir la nueva canción que seleccionaste con mucha energía.
3. El guión no debe exceder las 45 palabras. No incluyas acotaciones musicales ni hashtags.
4. Mantén la continuidad del programa considerando el historial de tus últimas interacciones.`;

    const messages: DialogueMessage[] = [
      { role: "system", content: systemPrompt },
      ...this.dialogueHistory,
    ];

    const triggerText = isInterlude
      ? "Es hora de tu locución y de programar el próximo tema. Utiliza herramientas si lo necesitas, selecciona la canción de la biblioteca y escribe el guión final."
      : "Selecciona el próximo tema para programar en la cola. Utiliza herramientas si lo necesitas, y responde con la selección final (deja 'dj_script' vacío).";

    messages.push({ role: "user", content: triggerText });

    // Loop for tool calls (max 3 turns)
    for (let turn = 0; turn < 4; turn++) {
      try {
        const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
          method: "POST",
          headers: {
            Authorization: `Bearer ${apiKey}`,
            "Content-Type": "application/json",
            "HTTP-Referer": "https://github.com/srsergi0/radio-bloom",
            "X-Title": "Radio Bloom",
          },
          body: JSON.stringify({
            model,
            messages,
            temperature: 0.7,
            response_format: { type: "json_object" },
          }),
        });

        if (!res.ok) {
          throw new Error(`OpenRouter returned status ${res.status}: ${await res.text()}`);
        }

        const data = (await res.json()) as any;
        const content = data.choices?.[0]?.message?.content?.trim();
        if (!content) return null;

        const cleanedContent = content
          .replace(/^```json\s*/i, "")
          .replace(/```$/, "")
          .trim();
        const parsed = JSON.parse(cleanedContent);

        if (parsed.action === "call_tool" || parsed.action === "use_tool") {
          const toolName = parsed.tool;
          const toolArgs = parsed.arguments || {};
          console.log(`[OrchestratorService] Agent called tool: ${toolName} with args:`, toolArgs);

          const toolResult = await this.executeTool(toolName, toolArgs);

          // Add assistant call and tool result to context
          messages.push({ role: "assistant", content: cleanedContent });
          messages.push({
            role: "user",
            content: `Resultado de la herramienta ${toolName}: ${toolResult}`,
          });

          continue; // Next turn
        }

        if (parsed.action === "final_response") {
          return {
            selectedSongId: parsed.selected_song_id,
            djScript: parsed.dj_script || undefined,
          };
        }

        throw new Error(`Acción de agente desconocida: ${parsed.action}`);
      } catch (err: any) {
        console.error(`[OrchestratorService] Error in agent turn ${turn}:`, err.message);
        break;
      }
    }

    return null;
  }

  /**
   * Executes one of the registered project-specific or weather tools.
   */
  private async executeTool(name: string, args: any): Promise<string> {
    try {
      switch (name) {
        case "search_library": {
          const query = args.query || "";
          const results = this.libraryRepo.search(query, 15);
          return JSON.stringify(
            results.items.map((s) => ({
              id: s.id,
              title: s.title,
              artist: s.artist || "Desconocido",
              album: s.album || "",
              file: s.file,
            }))
          );
        }
        case "get_library_stats": {
          const totalSongs = this.libraryRepo.countTracks("song");
          const totalInterludes = this.libraryRepo.countTracks("interludio");
          return JSON.stringify({ totalSongs, totalInterludes });
        }
        case "get_stream_status": {
          const status = await this.liquidsoapService.getStreamStatus();
          const queue = await this.liquidsoapService.queueList();
          return JSON.stringify({
            playing: status.playing,
            currentTrack: status.title
              ? `"${status.title}" de ${status.artist || "Desconocido"}`
              : null,
            elapsed: status.elapsed,
            duration: status.duration,
            queue: queue.map((q) => q.title),
          });
        }
        case "get_current_time": {
          return new Date().toLocaleTimeString("es-ES", { hour: "numeric", minute: "2-digit" });
        }
        default:
          return `Herramienta "${name}" no encontrada.`;
      }
    } catch (err: any) {
      return `Error ejecutando herramienta: ${err.message}`;
    }
  }

  /**
   * Synthesize script using Edge-TTS.
   */
  private async synthesizeSpeech(scriptText: string): Promise<string | null> {
    const voice = process.env.AI_DJ_VOICE || "es-ES-AlvaroNeural";
    try {
      const filename = `ai_dj_${Date.now()}_${Math.random().toString(36).slice(2, 6)}.mp3`;
      const interludiosDir = join(this.musicDir, "interludios");
      const localPath = join(interludiosDir, filename);

      const tts = new EdgeTTS(scriptText, voice);
      const result = await tts.synthesize();
      const arrayBuffer = await result.audio.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);
      writeFileSync(localPath, buffer);

      console.log(`[OrchestratorService] Voice synthesis completed: ${localPath}`);
      return localPath;
    } catch (err: any) {
      console.error("[OrchestratorService] Voice synthesis failed:", err.message);
      return null;
    }
  }
}
